version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: unit-2-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
#      TODO in variables
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profitsoft-unit-2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 8s
      timeout: 4s
      retries: 2
    networks:
      - unit-2

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: unit-2-backend
#    ports:
#      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy
#    networks:
#      - unit-2

volumes:
  pg_data:
    driver: local

networks:
  unit-2:
    driver: bridge