server:
  port: 8080

spring:
  application:
    name: profitsoft-unit-2
  datasource:
#   TODO localhost in variables
    url: jdbc:postgresql://localhost:5432/profitsoft-unit-2
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update



