server:
  port: 8080

spring:
  application:
    name: profitsoft-unit-2
  datasource:
    url: jdbc:postgresql://localhost:5432/profitsoft-unit-2
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
  kafka:
    bootstrap-servers: 'localhost:9092'

kafka:
  topics:
    reporterTopic: reporter-mails
    assigneeTopic: assignee-mails

